---
title: "Speed Dating Questions to Build Connections"
subtitle: "By Vanessa Van Edwards"
date: "2025-01-05"
--- 

> ## [Link to Blog](https://www.scienceofpeople.com/speed-dating-questions/)

# My personal favorites

A preface - these are great for actual *dates*, but can also be used in conversation with friends or acquaintances to level-up your connection.

I've also curated this list to include only the questions that I think *I* could also answer to an extensive degree. Can't have me looking stupid if the other party asks hbu. 

## Fun
1. Would you rather be able to communicate with all animals, or speak all foreign languages?

## Self
1. What is something you're looking forward to in the next few weeks / months?
2. What is a project or goal that you're currently working on that excites you?
3. How do you manage stress?
4. What is your favorite time of the day?

## Background
1. Where did you grow up?
2. Do you have any siblings? Tell me about them.
3. What was high school like?
4. How did your childhood experiences shape who you are today?
5. What is your favorite childhood memory?
6. Do you have any family members you particularly admire? Why?
7. How did your family influence your educational or career choices?
8. Who had the biggest impact on your life growing up, and why?
9. What are your friends like?

## Hobbies and Interests
1. How do you like to spend your free time?
2. What is the hobby that you are most passionate about?
3. What is the most recent hobby that you've picked up?
4. What is a hobby you've always wanted to try, but haven't yet?
5. What kind of music do you like?
6. Do you play a musical instrument? (If no, what musical instrument would you like to learn?)
7. What is a book you think everyone should read / what is your favorite book?
8. Do you have any interests that you think would surprise people?
9. What is one thing you want to learn or do in the next year?
10. What is a subject you wish you knew more about?

## Relationships
1. What are you looking for in a relationship right now?
2. What qualities do you value most in a partner? / What is the number one quality you look for in a partner?
3. How do you define a successful relationship?
4. What is one lesson you've learned from past relationships?
5. What is a relationship deal-breaker for you?
6. What do you think is the most annoying thing about dating these days?

## Career
1. What is your dream job?
2. What are your biggest professional goals for the next few years?
3. What inspired you to choose your current career path?

## Social media
1. What is your most-used social media platform?
2. Do you think social media brings people closer together or drives them apart?

## Deeper
1. What does happiness mean to you?
2. How do you measure success in life beyond career achievements?
3. What is the best piece of advice you've ever received?