project:
  type: website
  title: "Personal Encyclopedia"
  output-dir: /home/jasmine/PROJECTS/encyclopedia/docs

website:
  title: "Personal Encyclopedia"
  favicon: sunflower.png
  
  page-navigation: true

  # navbar:
  #   background: "#B1BDCC"
  #   search: true
  #   center:
  #     - text: "Home"
  #       href: index.qmd
  #     - ideabank.qmd

  sidebar:
    # title: "Personal Encyclopedia"
    background: "#B1BDCC"
    logo: "sunflower.png"
    pinned: true
    align: center

    # tools:
    # - icon: github
    #   href: https://github.com/jasminex21/encyclopedia
    style: docked
    search: true
    contents:
      - href: index.qmd
        text: Home
      - href: ideabank.qmd
        text: Ideabank
      - text: "---"
      - section: Topics
        contents:
        - section: Psychology
          contents: topics/psychology/*
        - section: Computer Science
          contents: 
            - href: topics/computer_science/*
            - section: Natural Language Processing
              contents: topics/computer_science/nlp/*
        - section: Notes
          contents: topics/notes/*
format:
  html:
    theme: 
      light: [cosmo, theme.scss]
      # dark: [cosmo, dark.scss]
    css: styles.css 
    toc: true

editor:
  render-on-save: true