---
title: "Ideabank"
description: "Topics I want to look into 🤔"
--- 
> For additional ideas, [generate a random Wikipedia page...](https://en.wikipedia.org/wiki/Wikipedia:Random)

### Psychology
* Biological contributors to homicide
  * Sajous-Turner et al., 2020 ([Aberrant brain gray matter in murderers](https://link.springer.com/article/10.1007/s11682-019-00155-y))
  * Raine, 2013 ([The anatomy of violence: The biological roots of crime](https://psycnet.apa.org/record/2013-09813-000)) - this is a book
* The psychology of advertising and consumer behaviour - what psychological tactics are used in marketing and why do they work to influence consumer decisions?
* Cultural influences on behaviour and cognition
  * Individualism vs Collectivism (Hofstede's Dimensions)
* Attachment styles and their impact on adult romantic relationships
  * Specifically, I find avoidant attachment styles to be pretty interesting
* Why do people watch horror movies (when they are intended specifically to evoke fear and negative emotions in viewers)?
  * Andersen et al., 2021 ([Playing With Fear: A Field Study in Recreational Horror](https://journals.sagepub.com/doi/10.1177/0956797620972116))
* Psychiatric disorders as dynamical systems
  * Scheffer et al., 2024 ([A Dynamical Systems View of Psychiatric Disorders-Theory: A Review](https://pubmed.ncbi.nlm.nih.gov/38568615/))
  * [Tweet by Mitchell B. Slapik](https://x.com/mslapik/status/1860522739234132296?s=43)   

### Computer Science
* Topic modelling - an overview of what it is, how it works, and how to apply it
  * Blei, 2012 ([Probabilistic Topic Models](https://www.cs.columbia.edu/~blei/papers/Blei2012.pdf))
* Game Theory
  * Application of Game Theory - SHAP values in machine learning
* NLP - go through Dan Jurafsky and James H. Martin's [textbook](https://web.stanford.edu/~jurafsky/slp3/) 

### Linguistics
* Onomastics (the study of the history and origin of proper names, especially personal names) and nicknaming
  * Kennedy & Zamuner, 2006 ([Nicknames and the Lexicon of Sports](https://read.dukeupress.edu/american-speech/article/81/4/387/5450/NICKNAMES-AND-THE-LEXICON-OF-SPORTS))
  * Bechar-Israeli, 1995 ([From 〈Bonehead〉 to 〈cLoNehEad〉: Nicknames, Play, and Identity on Internet Relay Chat](https://academic.oup.com/jcmc/article/1/2/JCMC127/4584330))
* The impact of social media on political speech
  * Etymology Nerd's article [Algorithms are making political speech more extreme](https://www.usermag.co/p/algorithms-are-making-political-speech?utm_medium=ios&triedRedirect=true)
* Idiolects - the speech habits that are unique to specific people based on their own life experiences (education, sociological and geographical upbringing, etc.)
  * Inspired by this short article by The Etymology Nerd: [how to catch a gubernatorial candidate, or a domestic terrorist](https://etymology.substack.com/p/how-to-catch-a-gubernatorial-candidate?r=3uxy8z&utm_medium=ios&triedRedirect=true)
* Linguistic Game Theory
  * Inspired once again by The Etymology Nerd ([reel](https://www.instagram.com/reel/DC9YYsnOa79/?igsh=MXAybnppY3pvdndkNA==))
  * Game Theoretic Linguistics ([Applications of Game Theory in Linguistics](https://profgerhard.de/sfs/publications/compass.pdf))

### Ancient History
* Cassius Dio and his impact on Roman history
* Series of (evil) emperors / rulers / dictators and their reigns: 
  * Emperor Qin
  * Commodus
  * Caligula
  * Caracalla
    * *SPQR: A History of Ancient Rome* page 527 and on (Epilogue: The First Roman Millenium)
  * Nero
  * Nebuchadnezzar II of Babylon
  * Henry VI of England

### Astronomy
* Olbers' Paradox
  * Why is the sky dark at night? Via [Britannica](https://www.britannica.com/science/Olbers-paradox): "If the universe is endless and uniformly populated with luminous stars, then every line of sight must eventually terminate at the surface of a star. Hence, contrary to observation, this argument implies that the night sky should everywhere be bright, with no dark spaces between the stars."

### Marine Science
* Series of deep sea creatures
  * Giant Pacific Octopus
  * Colossal Squid
* Extinction of the megalodon - proof that it is truly extinct

### Philosophy
* The Simulation Argument - are we living in a simulation?
  * Via [Wikipedia](https://en.wikipedia.org/wiki/Simulation_hypothesis): "In 2001, philosopher Nick Bostrom proposed the simulation argument, which suggests that if a civilization becomes capable of creating conscious simulations, it could generate so many simulated beings that a randomly chosen conscious entity would almost certainly be in a simulation. The argument presents a trilemma: either such simulations are not created due to technological limitations or self-destruction; or advanced civilizations choose not to create them; or we are almost certainly living in one. This assumes that consciousness is not uniquely tied to biological brains but can arise from any system that implements the right computational structures and processes."

### Paleontology
* *Tiktaalik* and transition fossils
* My intention is to create an expanding repository of dinosaur genera, e.g., *Spinosaurus*, *Tyrannosaurus*, *Archaeopteryx*, etc., and map them under a broad phylogenetic category (e.g., Saurischia>Sauropoda/Sauropodomorpha, Ornithischia>Marginocephalia, Saurischia>Theropoda sort of thing). It helps me to think about dinosaurs in terms of those classification categories. And then within each .qmd writeup I'll do a more specific breakdown of each dinosaurs' classification (e.g., for Psittacosaurus it would be Ornithischia>Marginocephalia>Ceratopsia, or for Spinosaurus it would be Saurischia>Therapoda>Spinosauridae). Still figuring out which broad categories I want to use as the folder names but probably Ornithischia (containing subfolders Thyreophora, Ornithopoda, Marginocephalia) and Saurischia (containing subfolders Sauropodomorpha and Theropoda), and depending on the size or distinctness of the groups within the subgroups (e.g., Ceratopsia might warrant its own folder) I'll make more subgroups. I can do species specifications within the genera writeup (S. mirabilis vs S. aegyptiacus). Oh and probably I will have dinosauromorphs in a separate folder as well (but make the clarification that Dinosauromorpha includes Dinosauria; they are not separate lineages)
  * Prior to writing up each dino group, I'll establish the context of Dinosauria by writing:
    * A breakdown of where dinosaurs are located phylogenetically, and how they are further broken down within Dinosauria
    * Geologic Time Scale - a quick breakdown of the Mesosoic Era and what exactly demarcates the boundary btwn the Permian and Triassic (significance of Permo-Triassic extinction), what broadly is going on (in terms of species diversity, mainly) the each of the Triassic, Jurassic, and Cretaceous periods, the "end" of dinosaurs at the end Cretaceous 66Ma. Also, what was going on in the Permian with regards to the evolution of archosaurs (but also synapsids). For the Permian, talk about Dimetrodon and Tiktaalik, gorgonopsians, dicynodonts, rhynchosaurs
  * Sauropods deserve a whole writeup imo. Mentioned them in the Saurischia writeup but kinda briefly; there is so much that can be said about them, specifically regarding their evolution from proto-sauropods in the Triassic to sauropods in the Jurassic-Cretaceous, and also how they got so large and how they were able to sustain their size (air sacs, breathing efficiency...). Brusatte wrote a good amount about this in his book so use that as a reference too. 
  * Specific genera I will write up (note I am also going to include dinosauromorphs here):
    * Spinosaurus
    * Triceratops
    * Psittacosaurus
    * T. rex
    * Iguanodon
    * Hadrosaur
    * Pachycephalosaur
    * Haolong
    * Anchiornis
    * Caihong
    * Compsognathus
    * Allosaurus
    * Diplodocus
    * Dreadnaughtus
    * Brachiosaurus
    * Argentinosaurus
    * Yutyrannus
    * Marasuchus
    * Heterodontosaurus
    * Plateosaurs
    * Suchomimus
    * Baryonyx
    * Ceratosaurus
    * Carnosaurus
  * I also want to include:
    * marine reptiles - Ichthyosaurs, Mosasaurs, Plesiosaurs
    * pterosaurs - absolutely Quetzalcoatlus and Hatzegopteryx 
    * (although now that I'm thinking about it, I'll probably make separate major sections for Dinosauria, Pterosauria, and whatever the marine reptiles category is)

### Bioinformatics / Computational Biology
* [AVADA: toward automated pathogenic variant evidence
retrieval directly from the full-text literature](https://www.gimjournal.org/article/S1098-3600(21)01282-X/pdf)
  * I'm super interested in their approach - I can learn a lot from this.